### ISSUE TITLE
Getting exception adding plugin

### ISSUE THREAD

**Issue by gotto2002** [RafPe/serverless-reqvalidator-plugin#22]
I am getting the following exception after installing the plugin (and documentation plugin) and just adding the plugin references to my serverless.yml file.  I haven't added anything else to the yml file yet, just the plugin references.

TypeError: serverless.configSchemaHandler.defineFunctionEventProperties is not a function
      at new ServerlessReqValidatorPlugin (c:\git\LeakAlert\UserService\node_modules\serverless-reqvalidator-plugin\src\index.js:50:36)
      at PluginManager.addPlugin (c:\git\LeakAlert\UserService\node_modules\serverless\lib\classes\PluginManager.js:94:28)
      at c:\git\LeakAlert\UserService\node_modules\serverless\lib\classes\PluginManager.js:129:31
      at Array.forEach (<anonymous>)
      at PluginManager.loadAllPlugins (c:\git\LeakAlert\UserService\node_modules\serverless\lib\classes\PluginManager.js:129:8)
      at c:\git\LeakAlert\UserService\node_modules\serverless\lib\Serverless.js:88:39
      at tryCatcher (c:\git\LeakAlert\UserService\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (c:\git\LeakAlert\UserService\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (c:\git\LeakAlert\UserService\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (c:\git\LeakAlert\UserService\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (c:\git\LeakAlert\UserService\node_modules\bluebird\js\release\promise.js:729:18)
      at Promise._fulfill (c:\git\LeakAlert\UserService\node_modules\bluebird\js\release\promise.js:673:18)
      at Promise._settlePromise (c:\git\LeakAlert\UserService\node_modules\bluebird\js\release\promise.js:617:21)
      at Promise._settlePromise0 (c:\git\LeakAlert\UserService\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (c:\git\LeakAlert\UserService\node_modules\bluebird\js\release\promise.js:729:18)
      at Promise._fulfill (c:\git\LeakAlert\UserService\node_modules\bluebird\js\release\promise.js:673:18)
      at Promise._resolveCallback (c:\git\LeakAlert\UserService\node_modules\bluebird\js\release\promise.js:466:57)
      at Promise._settlePromiseFromHandler (c:\git\LeakAlert\UserService\node_modules\bluebird\js\release\promise.js:559:17)
      at Promise._settlePromise (c:\git\LeakAlert\UserService\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (c:\git\LeakAlert\UserService\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (c:\git\LeakAlert\UserService\node_modules\bluebird\js\release\promise.js:729:18)
      at Promise._fulfill (c:\git\LeakAlert\UserService\node_modules\bluebird\js\release\promise.js:673:18)
      at PromiseArray._resolve (c:\git\LeakAlert\UserService\node_modules\bluebird\js\release\promise_array.js:127:19)
      at PromiseArray._promiseFulfilled (c:\git\LeakAlert\UserService\node_modules\bluebird\js\release\promise_array.js:145:14)
      at Promise._settlePromise (c:\git\LeakAlert\UserService\node_modules\bluebird\js\release\promise.js:609:26)
      at Promise._settlePromise0 (c:\git\LeakAlert\UserService\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (c:\git\LeakAlert\UserService\node_modules\bluebird\js\release\promise.js:729:18)
      at Promise._fulfill (c:\git\LeakAlert\UserService\node_modules\bluebird\js\release\promise.js:673:18)
      at Promise._resolveCallback (c:\git\LeakAlert\UserService\node_modules\bluebird\js\release\promise.js:466:57)
      at Promise._settlePromiseFromHandler (c:\git\LeakAlert\UserService\node_modules\bluebird\js\release\promise.js:559:17)
      at Promise._settlePromise (c:\git\LeakAlert\UserService\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (c:\git\LeakAlert\UserService\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (c:\git\LeakAlert\UserService\node_modules\bluebird\js\release\promise.js:729:18)
      at Promise._fulfill (c:\git\LeakAlert\UserService\node_modules\bluebird\js\release\promise.js:673:18)
      at PropertiesPromiseArray.PromiseArray._resolve (c:\git\LeakAlert\UserService\node_modules\bluebird\js\release\promise_array.js:127:19)
      at PropertiesPromiseArray._promiseFulfilled (c:\git\LeakAlert\UserService\node_modules\bluebird\js\release\props.js:78:14)
      at Promise._settlePromise (c:\git\LeakAlert\UserService\node_modules\bluebird\js\release\promise.js:609:26)
      at Promise._settlePromise0 (c:\git\LeakAlert\UserService\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (c:\git\LeakAlert\UserService\node_modules\bluebird\js\release\promise.js:729:18)
      at _drainQueueStep (c:\git\LeakAlert\UserService\node_modules\bluebird\js\release\async.js:93:12)
      at _drainQueue (c:\git\LeakAlert\UserService\node_modules\bluebird\js\release\async.js:86:9)
      at Async._drainQueues (c:\git\LeakAlert\UserService\node_modules\bluebird\js\release\async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (c:\git\LeakAlert\UserService\node_modules\bluebird\js\release\async.js:15:14)
      at processImmediate (internal/timers.js:456:21)
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          win32
     Node Version:              12.16.0
     Framework Version:         1.83.2 (local)
     Plugin Version:            3.8.4
     SDK Version:               2.3.2
     Components Version:        2.34.9
 

Command finished.

**Comment by RafPe** [comment]
Hi @gotto2002 - please check release notes ( might be that you are using outdated SLS ). 

This has been already asked in #19 #20 #21 and comes down to either upgrading of framework or pinning to 1.0.3
